name: maxminddb
description: A library for querying MaxMind databases. (.mmdb)
repository: https://github.com/fischerscode/dart-maxminddb
version: 1.3.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  extendedip: ^1.0.0

dev_dependencies:
  lint: ^2.0.0
  test: ^1.17.12
