name: maxminddb
description: A library for querying MaxMind databases (like GeoLite2-City.mmdb).
repository: https://github.com/EvgeniShmakov/dart-maxmindDB
version: 1.4.2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  args: 2.4.2
  extendedip: 1.0.0

dev_dependencies:
  lint: 2.0.0
  test: 1.17.12
