name: maxminddb
description: A library for querying MaxMind databases (like GeoLite2-City.mmdb).
repository: https://github.com/fischerscode/dart-maxminddb
version: 1.4.0

executables:
  maxminddb:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.2
  extendedip: ^1.0.0

dev_dependencies:
  lint: ^2.0.0
  test: ^1.17.12
